### PR TITLE
Past

### PR DESCRIPTION
**Pull request by lillyfwang**
We will have to merge this after we merge the "constrain_params_that_are_functions" branch, since this is based off of that one.

Highlights in this branch:
- Sast to Past (via Pythonizer) [addresses #52]
- Past to generated Python code (via Generator) [addresses #53]
- Function tests (normal, nested, anonymous)

### CODE REVIEW

**Comment by akalicki** [comment]
TODO before merge: add tests for "pulling up" anonymous functions. Depends on the constrain branch in order to allow these to exist.

**Comment by akalicki** [comment]
adorbs

**Comment by akalicki** [comment]
![clap](https://media.giphy.com/media/wijMRo7UZXSqA/giphy.gif

**Comment by alexandramedway** [comment]
Have we done the anonymous functions stuff yet?

**Comment by lillyfwang** [comment]
@alexandramedway not for the "pulling up" section because we need what @dannyech is working on in the sast, so we can add those after merging his work in (see @akalicki's comment above)

**Pull request merged**
